websocket_api.rb: process with pid 16674 started.
I, [2014-07-10T14:10:42.703642 #16674]  INFO -- : Connected to AMQP broker.
/home/yuva/.rvm/gems/ruby-2.1.1/gems/amqp-1.3.0/lib/amqp/session.rb:187:in `block in initialize': AMQP broker closed TCP connection before authentication succeeded: this usually means authentication failure due to misconfiguration. Settings are {:host=>"127.0.0.1", :port=>5672, :user=>"guest", :pass=>"[filtered]", :auth_mechanism=>"PLAIN", :vhost=>"/", :timeout=>nil, :logging=>false, :ssl=>false, :frame_max=>131072, :heartbeat=>0} (AMQP::PossibleAuthenticationFailureError)
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/amqp-1.3.0/lib/amqp/session.rb:646:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/amqp-1.3.0/lib/amqp/session.rb:646:in `unbind'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1438:in `event_callback'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/websocket_api.rb:29:in `<top (required)>'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/websocket_api_ctl:6:in `<main>'
websocket_api.rb: process with pid 22103 started.
I, [2014-07-10T17:56:52.823708 #22103]  INFO -- : Connected to AMQP broker.
websocket_api.rb: process with pid 2938 started.
I, [2014-07-10T18:08:39.810258 #2938]  INFO -- : Connected to AMQP broker.
websocket_api.rb: process with pid 25152 started.
I, [2014-07-14T17:38:14.563791 #25152]  INFO -- : Connected to AMQP broker.
E, [2014-07-14T17:38:14.804667 #25152] ERROR -- : [amqp] Detected TCP connection failure
/home/yuva/.rvm/gems/ruby-2.1.2/gems/amqp-1.3.0/lib/amqp/session.rb:182:in `block in initialize': Could not establish TCP connection to 127.0.0.1:5672 (AMQP::TCPConnectionFailed)
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/amqp-1.3.0/lib/amqp/session.rb:784:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/amqp-1.3.0/lib/amqp/session.rb:784:in `tcp_connection_failed'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/amqp-1.3.0/lib/amqp/session.rb:627:in `unbind'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:1438:in `event_callback'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /home/yuva/Desktop/arvind/peatio/peatio-master/lib/daemons/websocket_api.rb:29:in `<top (required)>'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/yuva/.rvm/gems/ruby-2.1.2/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/websocket_api_ctl:6:in `<main>'
